FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["HttpServerToGraylog/HttpServerToGraylog.csproj", "HttpServerToGraylog/"]
RUN dotnet restore "HttpServerToGraylog/HttpServerToGraylog.csproj"
COPY . .
WORKDIR "/src/HttpServerToGraylog"
RUN dotnet build "HttpServerToGraylog.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "HttpServerToGraylog.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HttpServerToGraylog.dll"]
